### PR TITLE
Fix issue #25

### PR DESCRIPTION
**Pull request by jburel**
See https://github.com/ome/omero-guide-ilastik/issues/25

This PR allows to create a conda environment using ``conda env create -n ilastik --file binder/environment.yml`` as described in https://omero-guides.readthedocs.io/projects/ilastik/en/latest/setup.html
This will also work using repo2docker.
Test on mac using ``conda env create -n ilastik --file binder/environment.yml`` 
Test on mybinder or by running locally ``repo2docker``

cc @tlambert03

### CODE REVIEW

**Comment by pwalczysko** [comment]
Built on Mac - build went fine, but the script is crashing, although the ID of the dataset is correct and the ilastik project is present.

```
(ilastik-test) pwalczysko@ls31618~/Work/omero-guide-ilastik$ python scripts/pixel_classification.py
Host [wss://workshop.openmicroscopy.org/omero-ws]: 
Username [trainer-1]: 
Password: 
Dataset ID [6210]: 
Traceback (most recent call last):
  File "scripts/pixel_classification.py", line 188, in <module>
    main()
  File "scripts/pixel_classification.py", line 180, in main
    analyze(conn, images, ilastik_project, new_dataset)
  File "scripts/pixel_classification.py", line 111, in analyze
    shell = app.main(args)
  File "/Users/pwalczysko/miniconda3/envs/ilastik-test/ilastik-meta/ilastik/ilastik/app.py", line 157, in main
    load_fn = _prepare_auto_open_project(parsed_args)
  File "/Users/pwalczysko/miniconda3/envs/ilastik-test/ilastik-meta/ilastik/ilastik/app.py", line 355, in _prepare_auto_open_project
    raise RuntimeError("Project file '" + parsed_args.project + "' does not exist.")
RuntimeError: Project file '../notebooks/pipelines/pixel-class-133.ilp' does not exist.
(ilastik-test) pwalczysko@ls31618~/Work/omero-guide-ilastik$ 
```

**Comment by jburel** [comment]
you need to run the script from the ``scripts`` folder
i.e.
```
cd scripts
python pixel_classification.py
```
We could make it more robust but this is outside the scope of this PR

**Comment by pwalczysko** [comment]
Ignore previous comment (deleted) - the script must be run from within the scripts directory, then it works.

**Comment by pwalczysko** [comment]
Following error report when running from my Mac (Option 1). But the error was not consequential, the script is successfully saving the probabilities as image to OMERO now). Similar error (also without detrimental effect) I can see on MyBinder.

```
ERROR 2021-01-22 16:14:45,286 PluginManager 51402 4401141184 Unable to import plugin: /Users/pwalczysko/miniconda3/envs/ilastik-test/ilastik-meta/ilastik/ilastik/plugins_default/tracking_ctc_export
Traceback (most recent call last):
  File "/Users/pwalczysko/miniconda3/envs/ilastik-test/lib/python3.7/site-packages/yapsy/PluginManager.py", line 518, in loadPlugins
    candidate_module = PluginManager._importModule(plugin_module_name, candidate_filepath)
  File "/Users/pwalczysko/miniconda3/envs/ilastik-test/lib/python3.7/site-packages/yapsy/PluginManager.py", line 584, in _importModule
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/Users/pwalczysko/miniconda3/envs/ilastik-test/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/Users/pwalczysko/miniconda3/envs/ilastik-test/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/pwalczysko/miniconda3/envs/ilastik-test/ilastik-meta/ilastik/ilastik/plugins_default/tracking_ctc_export.py", line 4, in <module>
    from skimage.external import tifffile
ModuleNotFoundError: No module named 'skimage.external'
ERROR:yapsy:Unable to import plugin: /Users/pwalczysko/miniconda3/envs/ilastik-test/ilastik-meta/ilastik/ilastik/plugins_default/tracking_ctc_export
Traceback (most recent call last):
  File "/Users/pwalczysko/miniconda3/envs/ilastik-test/lib/python3.7/site-packages/yapsy/PluginManager.py", line 518, in loadPlugins
    candidate_module = PluginManager._importModule(plugin_module_name, candidate_filepath)
  File "/Users/pwalczysko/miniconda3/envs/ilastik-test/lib/python3.7/site-packages/yapsy/PluginManager.py", line 584, in _importModule
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/Users/pwalczysko/miniconda3/envs/ilastik-test/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/Users/pwalczysko/miniconda3/envs/ilastik-test/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/pwalczysko/miniconda3/envs/ilastik-test/ilastik-meta/ilastik/ilastik/plugins_default/tracking_ctc_export.py", line 4, in <module>
    from skimage.external import tifffile
ModuleNotFoundError: No module named 'skimage.external'
```

**Comment by pwalczysko** [comment]
Both locally and on MyBinder the script and notebook respectively worked as expected.
The only thing which is surprising is that from MyBinder, the probability maps coming from ilastik have wrong Rnd settings in OMERO. The images appear black, but the values are there, and the settings can be fixed using the Min/Max button in iviewer.

**Comment by jburel** [comment]
The error is coming from the version of skimage that ilastik comes with. this has been fixed in newer version of ilastik.

**Comment by pwalczysko** [comment]
Even after I stopped the MyBinder, the rnd issue with images coming from the local Mac persists, see
https://workshop.openmicroscopy.org/webclient/?show=image-57506
(sorry, I was claiming that the problematic image is coming from MyBinder, but of course I had no idea - now I am sure the last one comes from the local build)

**Comment by jburel** [comment]
It seems to be a problem with the rnd settings in omero 
This is how it looks after moving the channel's sliders
Screenshot 2021-01-22 at 16 54 17

**Comment by pwalczysko** [comment]
Second time round, from MyBinder only, the rnd were just fine. I am not too worried about the rnd issue.

**Review by pwalczysko — APPROVED** [review]

**Pull request merged**
