### PR TITLE
Simplify load of zarr data

### PR DESCRIPTION
**Pull request by jburel**
Simplify the loading of zarr data
* Check that the "zarr" notebooks and scripts still work
* Add ``flake8`` check for python script

### CODE REVIEW

**Comment by pwalczysko** [comment]
repo2docker, then run the python zarr script. Expand details to see error.
<details>

```
analyse_dataset_ilastik.groovy  pixel_classification.py  pixel_classification_zarr.py
(notebook) pwalczysko@fd60074dacf2:~/scripts$ python pixel_classification_zarr.py
Host [wss://outreach.openmicroscopy.org/omero-ws]:
Username [trainer-1]:
Password:
Dataset ID [6161]:
INFO ilastik_main: Starting ilastik from "/srv/conda/envs/notebook".
INFO:ilastik_main:Starting ilastik from "/srv/conda/envs/notebook".
Starting ilastik from "/srv/conda/envs/notebook".
INFO ilastik_main: Resetting lazyflow thread pool with 2 threads.
INFO:ilastik_main:Resetting lazyflow thread pool with 2 threads.
INFO ilastik_main: Configuring lazyflow RAM limit to 2.0GiB
INFO:ilastik_main:Configuring lazyflow RAM limit to 2.0GiB
INFO lazyflow.utility.memory: Available memory set to 2.0GiB
INFO:lazyflow.utility.memory:Available memory set to 2.0GiB
WARNING 2020-05-07 11:01:05,410 memory 71 140688987060032 User specified memory exceeds memory physically available. Please check theconfiguration.
WARNING:lazyflow.utility.memory:User specified memory exceeds memory physically available. Please check theconfiguration.
WARNING 2020-05-07 11:01:06,107 __init__ 71 140688987060032 Failed to automatic tracking workflow; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
WARNING:ilastik.workflows.tracking.conservation:Failed to automatic tracking workflow; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
WARNING 2020-05-07 11:01:06,111 __init__ 71 140688987060032 Failed to import automatic tracking workflow (conservation tracking). For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
WARNING:ilastik.workflows:Failed to import automatic tracking workflow (conservation tracking). For this workflow, see theinstallationinstructions on our website ilastik.org; check dependencies: libemon.so.1.3.1: cannot open shared object file:No such file or directory
WARNING 2020-05-07 11:01:06,118 __init__ 71 140688987060032 Failed to import structured learning tracking workflow. For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: libemon.so.1.3.1: cannot openshared object file: No such file or directory
WARNING:ilastik.workflows:Failed to import structured learning tracking workflow. For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
INFO ilastik.shell.projectManager: Opening Project: ../notebooks/pipelines/pixel-class-133.ilp
INFO:ilastik.shell.projectManager:Opening Project: ../notebooks/pipelines/pixel-class-133.ilp
WARNING projectManager.py(158): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING projectManager.py(168): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING dataSelectionSerializer.py(385): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING featureSelectionSerializer.py(91): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING featureSelectionSerializer.py(96): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING featureSelectionSerializer.py(102): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING featureSelectionSerializer.py(122): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING opSimpleBlockedArrayCache.py(43): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
WARNING opSlicedBlockedArrayCache.py(141): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
WARNING featureSelectionSerializer.py(169): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING pixelClassificationSerializer.py(227): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
running ilastik using ../notebooks/pipelines/pixel-class-133.ilp and B1_C1.tif
ERROR 2020-05-07 11:01:07,885 excepthooks 71 140688987060032 Unhandled exception in thread: 'MainThread'
ERROR:ilastik.excepthooks:Unhandled exception in thread: 'MainThread'
ERROR 2020-05-07 11:01:07,887 excepthooks 71 140688987060032 Traceback (most recent call last):
  File "pixel_classification_zarr.py", line 186, in <module>
    main()
  File "pixel_classification_zarr.py", line 178, in main
    analyze(conn, images, ilastik_project, new_dataset)
  File "pixel_classification_zarr.py", line 126, in analyze
    [PreloadedArrayDatasetInfo(preloaded_array=input_data)],
  File "/srv/conda/envs/notebook/ilastik-meta/ilastik/ilastik/applets/dataSelection/opDataSelection.py", line 359, in __init__
    preloaded_array, axistags or get_default_axisordering(preloaded_array.shape)
AttributeError: 'NoneType' object has no attribute 'shape'

ERROR:ilastik.excepthooks:Traceback (most recent call last):
  File "pixel_classification_zarr.py", line 186, in <module>
    main()
  File "pixel_classification_zarr.py", line 178, in main
    analyze(conn, images, ilastik_project, new_dataset)
  File "pixel_classification_zarr.py", line 126, in analyze
    [PreloadedArrayDatasetInfo(preloaded_array=input_data)],
  File "/srv/conda/envs/notebook/ilastik-meta/ilastik/ilastik/applets/dataSelection/opDataSelection.py", line 359, in __init__
    preloaded_array, axistags or get_default_axisordering(preloaded_array.shape)
AttributeError: 'NoneType' object has no attribute 'shape'

(notebook) pwalczysko@fd60074dacf2:~/scripts$
(notebook) pwalczysko@fd60074dacf2:~/scripts$
(notebook) pwalczysko@fd60074dacf2:~/scripts$
(notebook) pwalczysko@fd60074dacf2:~/scripts$
(notebook) pwalczysko@fd60074dacf2:~/scripts$
(notebook) pwalczysko@fd60074dacf2:~/scripts$ python pixel_classification_zarr.py
Host [wss://outreach.openmicroscopy.org/omero-ws]:
Username [trainer-1]:
Password:
Dataset ID [6161]: 6161
INFO ilastik_main: Starting ilastik from "/srv/conda/envs/notebook".
INFO:ilastik_main:Starting ilastik from "/srv/conda/envs/notebook".
Starting ilastik from "/srv/conda/envs/notebook".
INFO ilastik_main: Resetting lazyflow thread pool with 2 threads.
INFO:ilastik_main:Resetting lazyflow thread pool with 2 threads.
INFO ilastik_main: Configuring lazyflow RAM limit to 2.0GiB
INFO:ilastik_main:Configuring lazyflow RAM limit to 2.0GiB
INFO lazyflow.utility.memory: Available memory set to 2.0GiB
INFO:lazyflow.utility.memory:Available memory set to 2.0GiB
WARNING 2020-05-07 11:02:36,671 memory 93 139966644131648 User specified memory exceeds memory physically available. Please check theconfiguration.
WARNING:lazyflow.utility.memory:User specified memory exceeds memory physically available. Please check theconfiguration.
WARNING 2020-05-07 11:02:37,206 __init__ 93 139966644131648 Failed to automatic tracking workflow; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
WARNING:ilastik.workflows.tracking.conservation:Failed to automatic tracking workflow; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
WARNING 2020-05-07 11:02:37,209 __init__ 93 139966644131648 Failed to import automatic tracking workflow (conservation tracking). For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
WARNING:ilastik.workflows:Failed to import automatic tracking workflow (conservation tracking). For this workflow, see theinstallationinstructions on our website ilastik.org; check dependencies: libemon.so.1.3.1: cannot open shared object file:No such file or directory
WARNING 2020-05-07 11:02:37,215 __init__ 93 139966644131648 Failed to import structured learning tracking workflow. For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: libemon.so.1.3.1: cannot openshared object file: No such file or directory
WARNING:ilastik.workflows:Failed to import structured learning tracking workflow. For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
INFO ilastik.shell.projectManager: Opening Project: ../notebooks/pipelines/pixel-class-133.ilp
INFO:ilastik.shell.projectManager:Opening Project: ../notebooks/pipelines/pixel-class-133.ilp
WARNING projectManager.py(158): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING projectManager.py(168): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING dataSelectionSerializer.py(385): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING featureSelectionSerializer.py(91): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING featureSelectionSerializer.py(96): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING featureSelectionSerializer.py(102): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING featureSelectionSerializer.py(122): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING opSimpleBlockedArrayCache.py(43): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
WARNING opSlicedBlockedArrayCache.py(141): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
WARNING featureSelectionSerializer.py(169): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING pixelClassificationSerializer.py(227): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
running ilastik using ../notebooks/pipelines/pixel-class-133.ilp and B1_C1.tif
ERROR 2020-05-07 11:02:38,828 excepthooks 93 139966644131648 Unhandled exception in thread: 'MainThread'
ERROR:ilastik.excepthooks:Unhandled exception in thread: 'MainThread'
ERROR 2020-05-07 11:02:38,829 excepthooks 93 139966644131648 Traceback (most recent call last):
  File "pixel_classification_zarr.py", line 186, in <module>
    main()
  File "pixel_classification_zarr.py", line 178, in main
    analyze(conn, images, ilastik_project, new_dataset)
  File "pixel_classification_zarr.py", line 126, in analyze
    [PreloadedArrayDatasetInfo(preloaded_array=input_data)],
  File "/srv/conda/envs/notebook/ilastik-meta/ilastik/ilastik/applets/dataSelection/opDataSelection.py", line 359, in __init__
    preloaded_array, axistags or get_default_axisordering(preloaded_array.shape)
AttributeError: 'NoneType' object has no attribute 'shape'

ERROR:ilastik.excepthooks:Traceback (most recent call last):
  File "pixel_classification_zarr.py", line 186, in <module>
    main()
  File "pixel_classification_zarr.py", line 178, in main
    analyze(conn, images, ilastik_project, new_dataset)
  File "pixel_classification_zarr.py", line 126, in analyze
    [PreloadedArrayDatasetInfo(preloaded_array=input_data)],
  File "/srv/conda/envs/notebook/ilastik-meta/ilastik/ilastik/applets/dataSelection/opDataSelection.py", line 359, in __init__
    preloaded_array, axistags or get_default_axisordering(preloaded_array.shape)
AttributeError: 'NoneType' object has no attribute 'shape'
```

</details>

**Comment by pwalczysko** [comment]
repo2docker, notebook

 pixel_classification_zarr 

All good, very nice run, the display at the end is more persuasive too (not sure why it looks better, but it does)

Umm, but i cannot find the attached zarr zip on image https://outreach.openmicroscopy.org/webclient/?show=image-55204

**Comment by jburel** [comment]
@pwalczysko for the script, the file was not found.
Let me double-check

**Comment by pwalczysko** [comment]
Repeated the notebook - again, all good, but indeed, nothing attached to the image https://github.com/ome/omero-guide-ilastik/pull/13#issuecomment-625189070 - looks like a bug.

**Comment by pwalczysko** [comment]
With the 

repo2docker

...zarr_idr notebook

All good, except

```
conn.close()

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-8dd0cd799055> in <module>
----> 1 conn.close()

NameError: name 'conn' is not defined

```

I just played for a while with the image, then went to the connection close cell. Did I run out of time ? I thought you have the ``keepAlive`` there ?

**Comment by jburel** [comment]
@pwalczysko found the problem with the script. Pushing a commit now

**Comment by jburel** [comment]
@pwalczysko I have the keepAlive. So maybe the method does not do its job!!

**Comment by pwalczysko** [comment]
The python script works now fine.

  - no crash
  - the probabilities image is saved as zip to the original image as indicated

**Comment by pwalczysko** [comment]
The notebook

pixel_classification_zarr

is still having the same problem as before - no zip attached to the image, albeit the notebook claims it did so.

**Comment by jburel** [comment]
We no longer save in the notebook. I will update the text

**Comment by pwalczysko** [comment]
> @pwalczysko I have the keepAlive. So maybe the method does not do its job!!

I rerun the idr notebook with the new rebuild of repo2docker after your last commit

```
conn.close()

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-8dd0cd799055> in <module>
----> 1 conn.close()

NameError: name 'conn' is not defined

```

this problem repeated

I cannot find any "keep" or "alive" strings in that notebook

Edit
But I can find the ``keepAlive`` in the pixel_classification_zarr notebook.
I guess the method is only in the non-idr notebook, not the idr one.

**Comment by pwalczysko** [comment]
All works fine, both the connection cell is gone from the idr notebook and the saving mesage from the non-idr one.

But, you still have one mention about saving in https://github.com/ome/omero-guide-ilastik/pull/13/commits/a3f3248770c899ebb7e9e3fc947a80546a6ee470#diff-5ee5d27912d0d28f0c5f6f030d10c413R137

Otherwise good to merge

**Pull request merged**
