### PR TITLE
Binder

### PR DESCRIPTION
**Pull request by jburel**
* Allow to build this repo and run notebooks alongside the guide.
* The notebooks were copied with the git history from training-notebooks
* This can be run:
    * locally: see instructions in README
    * mybinder: enter https://github.com/jburel/omero-guide-ilastik, branch binder

### CODE REVIEW

**Comment by pwalczysko** [comment]
In mybinder, executing the first cell

```
Failed to automatic tracking workflow; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
Failed to import automatic tracking workflow (conservation tracking). For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
Failed to import structured learning tracking workflow. For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
```

**Comment by pwalczysko** [comment]
``Load the ilastik projects linked to the dataset``

this cell had no output after I run it
The action which I expected in the cell above happened much lower, in a cell which is named very similarly. Confusing.

Screen Shot 2020-04-15 at 16 42 33

**Comment by pwalczysko** [comment]
After running the cell which executes the workflow, I get several repeats of the output

```
INFO ilastik_main: Starting ilastik from "/srv/conda/envs/notebook".

INFO:ilastik_main:Starting ilastik from "/srv/conda/envs/notebook".

Starting ilastik from "/srv/conda/envs/notebook".
INFO ilastik_main: Resetting lazyflow thread pool with 2 threads.

INFO:ilastik_main:Resetting lazyflow thread pool with 2 threads.

INFO ilastik_main: Configuring lazyflow RAM limit to 2.0GiB

INFO:ilastik_main:Configuring lazyflow RAM limit to 2.0GiB

INFO lazyflow.utility.memory: Available memory set to 2.0GiB

INFO:lazyflow.utility.memory:Available memory set to 2.0GiB

INFO ilastik.shell.projectManager: Opening Project: /tmp/tmpxel_n1pl/pixel-class-133.ilp

INFO:ilastik.shell.projectManager:Opening Project: /tmp/tmpxel_n1pl/pixel-class-133.ilp
WARNING projectManager.py(158): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING projectManager.py(168): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING dataSelectionSerializer.py(385): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING featureSelectionSerializer.py(91): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING featureSelectionSerializer.py(96): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING featureSelectionSerializer.py(102): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING featureSelectionSerializer.py(122): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING opSimpleBlockedArrayCache.py(43): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
WARNING opSlicedBlockedArrayCache.py(141): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
WARNING featureSelectionSerializer.py(169): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
WARNING pixelClassificationSerializer.py(227): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.

z:195 t:1 c:2 y:241 x:246
Downloading image B5_C3.tif
running ilastik using /tmp/tmpxel_n1pl/pixel-class-133.ilp and B5_C3.tif
INFO ilastik.applets.batchProcessing.batchProcessingApplet: Exporting to in-memory array.
...
```
and then

```
...
Saving Probabilities as an Image in OMERO
```

The first part seemed to go fairly quickly. But I do not see any images saved to OMERO. I can see a new dataset there called ``ilastik_probabilities_from_dataset_6107`` which has the right timestamp. But no images in it. Something is wrong with the saving.

Note: This cell still shows the start, meaning it is not considered to be finished. Something is hanging there ?

**Comment by jburel** [comment]
Saving the image takes a long time.

**Comment by jburel** [comment]
> `Load the ilastik projects linked to the dataset`
> 
> this cell had no output after I run it
> The action which I expected in the cell above happened much lower, in a cell which is named very similarly. Confusing.
> 
> Screen Shot 2020-04-15 at 16 42 33

I will write select the model to use.
The selection is then used in the next cell

**Comment by jburel** [comment]
> After running the cell which executes the workflow, I get several repeats of the output
> 
> ```
> INFO ilastik_main: Starting ilastik from "/srv/conda/envs/notebook".
> 
> INFO:ilastik_main:Starting ilastik from "/srv/conda/envs/notebook".
> 
> Starting ilastik from "/srv/conda/envs/notebook".
> INFO ilastik_main: Resetting lazyflow thread pool with 2 threads.
> 
> INFO:ilastik_main:Resetting lazyflow thread pool with 2 threads.
> 
> INFO ilastik_main: Configuring lazyflow RAM limit to 2.0GiB
> 
> INFO:ilastik_main:Configuring lazyflow RAM limit to 2.0GiB
> 
> INFO lazyflow.utility.memory: Available memory set to 2.0GiB
> 
> INFO:lazyflow.utility.memory:Available memory set to 2.0GiB
> 
> INFO ilastik.shell.projectManager: Opening Project: /tmp/tmpxel_n1pl/pixel-class-133.ilp
> 
> INFO:ilastik.shell.projectManager:Opening Project: /tmp/tmpxel_n1pl/pixel-class-133.ilp
> WARNING projectManager.py(158): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
> WARNING projectManager.py(168): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
> WARNING dataSelectionSerializer.py(385): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
> WARNING featureSelectionSerializer.py(91): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
> WARNING featureSelectionSerializer.py(96): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
> WARNING featureSelectionSerializer.py(102): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
> WARNING featureSelectionSerializer.py(122): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
> WARNING opSimpleBlockedArrayCache.py(43): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
> WARNING opSlicedBlockedArrayCache.py(141): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
> WARNING featureSelectionSerializer.py(169): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
> WARNING pixelClassificationSerializer.py(227): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
> 
> z:195 t:1 c:2 y:241 x:246
> Downloading image B5_C3.tif
> running ilastik using /tmp/tmpxel_n1pl/pixel-class-133.ilp and B5_C3.tif
> INFO ilastik.applets.batchProcessing.batchProcessingApplet: Exporting to in-memory array.
> ...
> ```
> 
> and then
> 
> ```
> ...
> Saving Probabilities as an Image in OMERO
> ```
> 
> The first part seemed to go fairly quickly. But I do not see any images saved to OMERO. I can see a new dataset there called `ilastik_probabilities_from_dataset_6107` which has the right timestamp. But no images in it. Something is wrong with the saving.
> 
> Note: This cell still shows the start, meaning it is not considered to be finished. Something is hanging there ?

I need to see how to turn off the debugger

**Comment by pwalczysko** [comment]
> Saving the image takes a long time.

Indeed, it saved something, the image appears black, maybe because I closed the Mybinder instance prematurely. This indeed took a very long time.

**Comment by jburel** [comment]
on my zarr branch, I now save the results as a zarr zip that I can then re-open and view.
I have tested the workflow and it is much quicker
zarr image (Ihave converted one of the image to zarr file) -> analyse in ilastik ->  save results as zarr

**Comment by jburel** [comment]
> In mybinder, executing the first cell
> 
> ```
> Failed to automatic tracking workflow; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
> Failed to import automatic tracking workflow (conservation tracking). For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
> Failed to import structured learning tracking workflow. For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: libemon.so.1.3.1: cannot open shared object file: No such file or directory
> ```

We do not need the conservation tracking.
Installing `` libemon.so.1.3.1`` is surprisingly not enough

**Comment by pwalczysko** [comment]
No output on the import cell now, good

**Comment by pwalczysko** [comment]
```
Saving Probabilities as an Image in OMERO
z: 0/194
z: 1/194
z: 2/194
...
```

that is better, now I know what is going on

**Comment by jburel** [comment]
@pwalczysko ok if I merge it so I can move forward with the next steps?

**Comment by pwalczysko** [comment]
Yes, looks good to me.

**Comment by jburel** [comment]
Thanks merging

**Pull request merged**
