### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by jburel**
This PR bumps the version of ilastik and uses the meta-package.
This is the only way I managed to get it to work again
``h5py`` is capped otherwise it does not work with binder
The way the input array is passed has been modified in both scripts and notebooks
cc @pwalczysko

### CODE REVIEW

**Comment by joshmoore** [comment]
Did `h5py` drop support or break an API or something?

**Comment by jburel** [comment]
No this is due to ``mamba`` that is used during the build process by repo2docker 
see https://github.com/h5py/h5py/issues/1880

**Review by joshmoore — APPROVED** [review]
The basic changes all look good. :+1: (Obviously, ipynb diffs are always a bit problematic.)

**Comment by pwalczysko** [comment]
MyBinder, idr0062_pixel_classification_zarr.ipynb notebook

```
Error loading notebook

Unreadable Notebook: /home/jovyan/notebooks/idr0062_pixel_classification_zarr.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')
```

Repeated this error also locally - repo2docker

**Comment by jburel** [comment]
thanks @pwalczysko. I was cleaning the notebooks and probably cleaned too much :-)

**Comment by pwalczysko** [comment]
the other two notebooks worked fine.

**Comment by jburel** [comment]
@pwalczysko it should be fixed now

**Comment by pwalczysko** [comment]
> @pwalczysko it should be fixed now

Yes, tested on MyBinder, and the notebook works as expected now.
Interestingly, I noticed a warning (see screenshot below).

Screenshot 2021-04-30 at 17 06 22

Looks good to me.

**Comment by jburel** [comment]
Merging. 
I will push a new tag and update the value in itr
cc @sbesson

**Pull request merged**
