### PR TITLE
fix installation

### PR DESCRIPTION
**Pull request by jburel**
Remove usage of ilastik-dependencies-no-solvers==1.4 some uncapped ilastik packages have been modified and broke the build. Nobody can use the guide at the moment and run the notebook

This PR will allow the build to complete and the notebook to be run.
You will see few warning but they can be ignored

To test: run notebook ``idr0062_pixel_classification_zarr_idr.ipynb`` locally or https://mybinder.org/v2/gh/jburel/omero-guide-ilastik/fix_install?filepath=notebooks/idr0062_pixel_classification_zarr.ipynb

When approved and merged, tag 0.2.0

### CODE REVIEW

**Comment by jburel** [comment]
I have renamed the notebooks cc @sbesson

**Comment by sbesson** [comment]
What's the reason for the `idr` redundancy in `idr0062_pixel_classification_zarr_idr.ipynb` as opposed to `idr0062_pixel_classification_zarr.ipynb` ?

**Comment by jburel** [comment]
one directly connect to idr one only use idr data that have been moved to outreach/workshop
Edit: I am only going to rename the one that is pointing to idr and drop idr0062 from the "outreach" ones

**Comment by dominikl** [comment]
Looks good to me, notebook still working (tested on mybinder) 👍

**Pull request merged**
