### PR TITLE
Labels support

### PR DESCRIPTION
**Pull request by jburel**
* Fix installation of ilastik
* Change the image id, load "zarr" labels and compare the output of ilastik and the labels
[ilastik.mp4.zip](https://github.com/ome/omero-guide-ilastik/files/5512238/ilastik.mp4.zip)

### CODE REVIEW

**Comment by pwalczysko** [comment]
comment on the video in https://openmicroscopy.slack.com/archives/C011XLYFHUY/p1605029056002200

**Comment by pwalczysko** [comment]
repo2docker run locally fails for me with 

```
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... Killed
Removing intermediate container 6d6f9a04f1f9
The command '/bin/sh -c conda env update -p ${NB_PYTHON_PREFIX} -f "binder/environment.yml" && conda clean --all -f -y && conda list -p ${NB_PYTHON_PREFIX}' returned a non-zero code: 137
```

**Comment by pwalczysko** [comment]
on mybinder, all worked as expected.

**Comment by jburel** [comment]
@pwalczysko I think you are having the same problem locally than the one I had last week
I had to create a new conda env with repo2docker master  branch

**Comment by pwalczysko** [comment]
Yes, thank you, after

``pip install https://github.com/jupyterhub/repo2docker/archive/master.zip``

things started to work on repo2docker.

All looks good here, except the overarching strangeness with the cut-off image, see https://github.com/ome/omero-analysis-desktop/pull/3#issuecomment-725411362

To me it looks like if you were fetching just part of the data from S3 - which is fine, but your comment in https://github.com/ome/omero-analysis-desktop/pull/3#issuecomment-725269524 suggests that this is not the case and it is not expected @jburel  ?

**Comment by pwalczysko** [comment]
See https://github.com/ome/omero-analysis-desktop/pull/3#issuecomment-725975410 for the truncation problem - it is solved.

ready to mrege fmpov

**Pull request merged**
